apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-v0
  labels:
    app: user-service
    version: v0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
      version: v0
  template:
    metadata:
      labels:
        app: user-service
        version: v0
    spec:
      containers:
        - name: user-service
          image: vickydeploys/user-service-v1:latest
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
